namespace SpriteKind {
    export const conductor = SpriteKind.create()
}
function startLevel () {
    if (currentLvl == 1) {
        musicSheet = null;
    } else if (currentLvl == 2) {
        musicSheet = null;
    } else if (currentLvl == 3) {
        musicSheet = null;
    } else {
        game.over(true, effects.confetti)
    }
}
let currentLvl = 0
let musicSheet = null
// Global Numeric Variables (accessible to all functions)
currentLvl = 1


tiles.setCurrentTilemap(tilemap`level1`)
scene.setBackgroundImage(assets.image`imgConcertHall`)
// let mySprite = sprites.create(img`
//     ..............................
//     ..............................
//     ..............................
//     ..............................
//     ..............................
//     ..............................
//     .....................f........
//     .............fffff...f........
//     ............fffffff..f........
//     ...........fffffffff.f........
//     ...........f111f111f.f........
//     .........1.f1f1f1f1f.1........
//     ........ff.f111f111f.ff.......
//     ........ff.f1144411f.ff.......
//     ........ff.fff141fff.ff.......
//     ........fff...f1f...fff.......
//     ........ffffff111ffffff.......
//     .........fffff111fffff........
//     ..........ffff111ffff.........
//     ...........fff111fff..........
//     ............ff111ff...........
//     ............ff111ff...........
//     ............ff111ff...........
//     ............ffcccff...........
//     ............fffffff...........
//     .............fffff............
//     .............fffff............
//     .............fffff............
//     .............fffff............
//     ............444.444...........
//     `, SpriteKind.Player)
// scene.cameraFollowSprite(mySprite)
// controller.moveSprite(mySprite)
// mySprite.setPosition(15, 210)

